### PR TITLE
Mercury parser api

### PR DESCRIPTION
**Pull request by churchs19**
With the coming deprecation of the Readability API, Readability is
guiding developers to its replacement at
https://mercury.postlight.com/web-parser. This update adds support for
the Mercury API endpoint. The Mercury API returns identical JSON as the
existing Readability service, so the content replacement behavior
remains unchanged.

### CODE REVIEW

**Comment by Muffo** [comment]
This is very interesting!

I knew that Readability was planning to do some changes to the API but my understanding was that the existing one would have continued to work.
Is there a timeline for this changes?

**Comment by churchs19** [comment]
I'm not sure. Yesterday afternoon the Readability API stopped working entirely for me and the Readability.com page just had a link to Mercury without any option to sign in. Today, Readability.com is back to where it was before, with the old September 30, 2016 notification on top, so I honestly don't know.

**Comment by churchs19** [comment]
The last update of any sort from the Readability team on their blog or Twitter was on September 2 at https://medium.com/@readability/an-important-announcement-for-all-readability-api-users-32dbee232b29#.7wiqzfngc.

**Comment by Muffo** [comment]
Now I remember that I received an email to inform about the changes in the API.

I think that the relevant part for the extension is:

> Second, the vastly more popular Readability Parser API, which extracts article content from web pages, will continue to run and will improve.


However, I think it would be great to add another API and give an alternative to the users.
I did not know about Mercury but I am happy to integrate it :)

**Comment by churchs19** [comment]
I received the same email from them. The home page today is back to the one I saw 2 days ago with the pointer to Mercury. No idea what's going on with them at this point. :)

**Comment by Muffo** [comment]
Many thanks for this pull request!

**Pull request closed without merging**
